version: '3'

services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "25566:19132/udp"
    environment:
      - MEMORY=6G
      - VERSION=1.21.5
      - TYPE=PAPER
      - EULA=TRUE
      - SERVER_PORT=25565
      - DIFFICULTY=normal
      - ALLOW_NETHER=true
      - ENABLE_COMMAND_BLOCK=true
      - LEVEL_TYPE=default
      - PVP=true
      - MAX_PLAYERS=20
      - VIEW_DISTANCE=8
      - SIMULATION_DISTANCE=6
      - SPAWN_PROTECTION=16
      - GEYSER_DOWNLOAD_URL=https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
      - FLOODGATE_DOWNLOAD_URL=https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      - OVERRIDE_SERVER_PROPERTIES=true
    volumes:
      - /var/lib/minecraft/data:/data
      - /var/lib/minecraft/world:/data/world
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 7G
        reservations:
          memory: 4G 