version: '3'

services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    ports:
      - "25565:25565"   # Puerto Java
      - "19132:19132/udp"   # Puerto Bedrock
    environment:
      - MEMORY=4G
      - VERSION=1.20.4
      - TYPE=PAPER   # Cambiamos a Paper para mejor estabilidad
      - EULA=TRUE
      - SERVER_PORT=25565
      - DIFFICULTY=normal
      - ALLOW_NETHER=true
      - ENABLE_COMMAND_BLOCK=true
      - PVP=true
      - MAX_PLAYERS=20
      - VIEW_DISTANCE=8
      - SIMULATION_DISTANCE=6
      - SPAWN_PROTECTION=16
      - ONLINE_MODE=false   # Necesario para Geyser
      - OVERRIDE_SERVER_PROPERTIES=true
      - FORCE_REDOWNLOAD=true
      - UID=1000
      - GID=1000
    volumes:
      - ./data:/data
    restart: unless-stopped
    user: 1000:1000
    deploy:
      resources:
        limits:
          memory: 5G
        reservations:
          memory: 4G 