version: '3'

services:
  minecraft:
    build: .
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    environment:
      - MEMORY=2G
      - VERSION=1.21.4
      - TYPE=PAPER
      - EULA=TRUE
      - SERVER_PORT=25565
      - DIFFICULTY=normal
      - ALLOW_NETHER=true
      - ENABLE_COMMAND_BLOCK=true
      - LEVEL_TYPE=default
      - PVP=true
      - MAX_PLAYERS=20
      - VIEW_DISTANCE=10
      - SPAWN_PROTECTION=16
      - GEYSER=true
      - GEYSER_PORT=19132
      - FLOODGATE=true
      - PLUGINS_SYNC_UPDATE=false
      - COPY_PLUGINS_ONLY_IF_NEWER=false
      - SYNC_SKIP_NEWER_IN_DESTINATION=true
      - PLUGINS=https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot,https://github.com/ViaVersion/ViaVersion/releases/download/5.3.2/ViaVersion-5.3.2.jar
    volumes:
      - minecraft-data:/data
    restart: unless-stopped

volumes:
  minecraft-data:
    driver: local 